export const docs = [
  {
    id: 'intro',
    title: 'Introduction',
    section: 'FOUNDATIONS',
    content: [
      '# DocGen AI — Automated Documentation Engine',
      '',
      'Welcome to **DocGen AI**, the most advanced automated documentation platform for modern software teams. This guide walks you through everything you need to know to get maximum value from the platform.',
      '',
      '## What is DocGen AI?',
      '',
      'DocGen AI is a high-performance documentation synthesis engine that uses large language models (LLAMA 3.3, Groq L3) to analyze raw source code and produce professional-grade technical documentation in seconds.',
      '',
      '## Why DocGen AI?',
      '',
      'Manual documentation is one of the most expensive and error-prone activities in software engineering. Studies show that developers spend up to **30% of their time** writing and maintaining documentation.',
      '',
      'DocGen AI changes this permanently:',
      '',
      '- **Zero manual effort**: Paste your code, receive production-ready docs.',
      '- **Always up to date**: Regenerate documentation whenever your code changes.',
      '- **Multi-format output**: Docstrings, READMEs, API references, Mermaid diagrams, security audits, and test scaffolding — all from a single input.',
      '- **Sub-second latency**: Powered by Vercel Edge compute with global availability.',
      '',
      '## Core Capabilities',
      '',
      '### 1. Docstring Generation',
      'Automatically generates JSDoc, Python docstrings, Rustdoc, and JavaDoc-compatible comments for every function, class, and module in your codebase.',
      '',
      '### 2. README Synthesis',
      'Produces a fully-structured README.md including project description, installation instructions, usage examples, and contribution guidelines.',
      '',
      '### 3. API Reference',
      'Maps every exposed endpoint, function signature, and data type into a navigable, searchable API reference document.',
      '',
      '### 4. Architecture Diagrams',
      'Renders Mermaid-compatible flowcharts and system diagrams showing the logical relationships between modules, services, and dependencies.',
      '',
      '### 5. Security Audit',
      'Flags potential vulnerabilities including exposed secrets, SQL injection risks, unvalidated inputs, and insecure dependencies.',
      '',
      '### 6. Performance Report',
      'Analyses algorithmic complexity, identifies N+1 query patterns, and highlights bottlenecks with actionable recommendations.',
      '',
      '### 7. Test Scaffolding',
      'Generates Jest, Pytest, and Go test templates for uncovered functions with edge case suggestions.',
      '',
      '### 8. Quality Score',
      'Produces a 0–10 quality index based on naming conventions, cyclomatic complexity, duplication rate, and coverage estimates.',
      '',
      '## Supported Languages',
      '',
      '| Language | Docstrings | README | API Ref | Diagrams |',
      '|---|---|---|---|---|',
      '| TypeScript | Yes | Yes | Yes | Yes |',
      '| JavaScript | Yes | Yes | Yes | Yes |',
      '| Python | Yes | Yes | Yes | Yes |',
      '| Rust | Yes | Yes | Yes | Yes |',
      '| Go | Yes | Yes | Yes | Yes |',
      '| Java | Yes | Yes | Yes | Yes |',
      '| C++ | Yes | Yes | Yes | Yes |',
      '| Swift | Yes | Yes | Yes | Yes |',
      '',
      '## Getting Started',
      '',
      '1. Navigate to the **Studio** from the top navigation.',
      '2. Paste or upload your source code file.',
      '3. Select your programming language.',
      '4. Click **Run Neural Sync**.',
      '5. Browse the generated documentation across the output tabs.',
      '',
      '> **Tip**: For best results, submit focused modules of 100–500 lines.',
      '',
      '## Performance Benchmarks',
      '',
      '| Metric | Value |',
      '|---|---|',
      '| Average synthesis latency | Less than 0.8 seconds |',
      '| Global availability | 99.99% uptime |',
      '| Maximum input size | 50,000 tokens |',
      '| Concurrent sessions | Unlimited (Pro) |',
      '| Output formats | 8 document types |',
      '',
      '## Privacy & Data Handling',
      '',
      'Your source code is **never stored**. All synthesis occurs in a volatile memory buffer. The moment documentation is generated, the input payload is purged. DocGen AI operates under a strict zero-persistence architecture — your proprietary logic remains exclusively yours.',
      '',
      '## Future Roadmap',
      '',
      '### Q2 2026 — Stage 5 Analysis',
      'Support for complex multi-repository architectural maps, enabling cross-service dependency tracking across microservice ecosystems.',
      '',
      '### Q3 2026 — Visual Codebase Explorer',
      'An interactive, zoomable 3D map of your entire codebase\'s logical dependencies, rendered directly in the browser.',
      '',
      '### Q4 2026 — Voice Intelligence Bridge',
      'Collaborative documentation authoring via real-time voice dictation, enabling hands-free doc updates during live coding sessions.',
      '',
      '### Q1 2027 — Sovereign Lab Mode',
      'Fully localized processing for air-gapped environments and regulated industries (finance, healthcare, defence). Zero external API calls.',
      '',
      '## Enterprise Capabilities',
      '',
      'For large-scale organisations, DocGen AI offers an Enterprise tier designed for compliance, control, and volume.',
      '',
      '- **Single Sign-On (SSO)**: SAML 2.0 and OIDC integration with Okta, Azure AD, and Google Workspace.',
      '- **Custom LLM Routing**: Bring your own keys (BYOK) for Azure OpenAI, Anthropic, or specialized local models.',
      '- **Audit Logging**: Comprehensive, exportable audit trails of all platform activities and queries.',
      '- **Dedicated Instances**: Single-tenant infrastructure for maximum performance and isolation.',
      '',
      '## Integrations Ecosystem',
      '',
      'DocGen AI seamlessly connects with your existing developer toolchain:',
      '',
      '- **GitHub/GitLab/Bitbucket CI**: Automatically generate and open documentation PRs when new code is pushed.',
      '- **Slack/Teams Notifications**: Get alerted when codebase quality scores drop below established thresholds.',
      '- **Jira/Linear Automations**: Auto-attach technical summaries and dependency diagrams to tickets based on branch names.',
    ].join('\n')
  },
  {
    id: 'adv-core',
    title: 'Advanced Core',
    section: 'FOUNDATIONS',
    content: [
      '# Advanced Core Architecture',
      '',
      'This document describes the full technical architecture of the DocGen AI platform for engineering teams who want to understand what happens under the hood.',
      '',
      '## System Overview',
      '',
      'DocGen AI is built on a three-tier architecture:',
      '',
      'Browser (React/Vite) → Vercel Edge Functions → Groq AI Gateway → LLAMA 3.3 Model',
      '',
      'Each tier is independently scalable and fault-tolerant. The entire pipeline is stateless — no database is involved in the synthesis flow.',
      '',
      '## Tier 1: The Injection Layer (Frontend)',
      '',
      'The **Injection Layer** is a React 18 application bundled with Vite and deployed globally via Vercel CDN.',
      '',
      '### Key Responsibilities',
      '- Accept raw source code input via the Studio textarea or file upload.',
      '- Validate input size (max 50,000 tokens).',
      '- Detect programming language from file extension or content heuristics.',
      '- Open a Server-Sent Events (SSE) connection to the synthesis API.',
      '- Stream the real-time output into the appropriate documentation tabs.',
      '',
      '### State Management',
      'The Studio component uses React hooks with no external state library. All session state (code buffer, output, active tab) is ephemeral and cleared on page refresh.',
      '',
      '### Streaming Parser',
      'Incoming SSE frames are parsed in real time. A marker-based extraction system splits the single AI stream into 8 discrete sections (DOCSTRINGS, README, API_REF, DIAGRAM, SECURITY, PERFORMANCE, TESTS, QUALITY).',
      '',
      '## Tier 2: The Synthesis Layer (Edge Functions)',
      '',
      'The synthesis API runs as a Vercel Edge Function, giving it global distribution with cold-start times under 2ms.',
      '',
      '### Request Flow',
      '',
      '1. **Receive** POST request with code and language payload.',
      '2. **Sanitize** input — strip binary content, validate encoding.',
      '3. **Construct** a structured prompt with 8 explicit output sections.',
      '4. **Stream** the Groq API response back to the client via SSE.',
      '5. **Terminate** the connection cleanly when generation is complete.',
      '',
      '### Prompt Engineering',
      '',
      'The prompt is engineered to force the model to produce all 8 documentation sections in every response. The system prompt establishes the model as a senior technical writer with expertise in the submitted language.',
      '',
      '### Failover Mechanism',
      '',
      'If the Groq API is unavailable, the system switches to a local heuristic engine that generates a basic documentation scaffold. This guarantees the user always receives output.',
      '',
      '## Tier 3: The AI Model Layer (Groq)',
      '',
      'DocGen AI uses **Groq\'s LPU Inference Engine** with the **LLAMA 3.3 70B** model.',
      '',
      '### Why Groq?',
      'Groq\'s LPU (Language Processing Unit) architecture offers 10–100x faster inference than traditional GPU-based providers. This is why DocGen AI achieves sub-second synthesis for most inputs.',
      '',
      '## Latency Benchmarks',
      '',
      '| Tier | P50 | P95 | P99 |',
      '|---|---|---|---|',
      '| Edge Function startup | 2ms | 5ms | 12ms |',
      '| Groq first token | 180ms | 350ms | 600ms |',
      '| Total synthesis (500 LOC) | 0.8s | 1.4s | 2.1s |',
      '| Total synthesis (2000 LOC) | 1.8s | 3.2s | 5.0s |',
      '',
      '## Scalability',
      '',
      'Because all state is ephemeral and the architecture is fully serverless, DocGen AI scales to unlimited concurrent users without any infrastructure changes. Vercel automatically provisions additional edge nodes during traffic spikes.',
      '',
      '## Error Handling',
      '',
      'All errors are surfaced to the user through toast notifications with a brief explanation. The stream parser is resilient to malformed chunks and will continue processing even if individual SSE frames are corrupted.',
    ].join('\n')
  },
  {
    id: 'api-reference',
    title: 'API Reference',
    section: 'FOUNDATIONS',
    content: [
      '# API Reference',
      '',
      'Complete reference for all DocGen AI API endpoints.',
      '',
      '## Base URL',
      '',
      'Production: https://aalap-doc-generator.vercel.app/api',
      '',
      '---',
      '',
      '## POST /api/generate',
      '',
      'The core synthesis endpoint. Accepts raw source code and returns a real-time stream of generated documentation.',
      '',
      '### Request',
      '',
      '**Method:** POST',
      '**Content-Type:** application/json',
      '',
      '#### Request Body Fields',
      '',
      '| Field | Type | Required | Description |',
      '|---|---|---|---|',
      '| code | string | Yes | The source code to document |',
      '| language | string | Yes | e.g. typescript, python, rust, go |',
      '| advanced_mode | boolean | No | Enable deep reasoning (default: false) |',
      '| context | string | No | Global project context for better results |',
      '',
      '### Response',
      '',
      'Content-Type: text/event-stream',
      '',
      'The response is a Server-Sent Events (SSE) stream. Each event carries a JSON payload with a text field containing the next chunk of generated documentation.',
      '',
      '#### Output Sections',
      '',
      '| Marker | Section | Description |',
      '|---|---|---|',
      '| DOCGEN:DOCSTRINGS | Docstrings | Inline code comments for all functions/classes |',
      '| DOCGEN:README | README | Full README.md file |',
      '| DOCGEN:API_REF | API Reference | Endpoint/function signatures |',
      '| DOCGEN:DIAGRAM | Diagram | Mermaid architecture diagram |',
      '| DOCGEN:SECURITY | Security | Vulnerability analysis |',
      '| DOCGEN:PERFORMANCE | Performance | Complexity and bottleneck report |',
      '| DOCGEN:TESTS | Tests | Test scaffolding templates |',
      '| DOCGEN:QUALITY | Quality | Numeric quality score (0-10) |',
      '',
      '### Error Responses',
      '',
      '| Status | Error | Description |',
      '|---|---|---|',
      '| 400 | EMPTY_INPUT | Code field is empty or missing |',
      '| 413 | INPUT_TOO_LARGE | Input exceeds 50,000 token limit |',
      '| 500 | STREAM_FAILURE | Upstream AI service error |',
      '| 503 | AI_UNAVAILABLE | Groq API temporarily unreachable |',
      '',
      '---',
      '',
      '## GET /api/docs',
      '',
      'Returns the complete documentation knowledge base used to populate this Guide.',
      '',
      '---',
      '',
      '## Authentication',
      '',
      'The public endpoints require no authentication. Pro-tier features use a session-based token generated at initialization. The token is stored in sessionStorage and never transmitted to third parties.',
      '',
      '### Token Lifecycle',
      '',
      '1. User opens the Studio.',
      '2. A unique session token is generated client-side.',
      '3. The token is attached to all Pro API requests.',
      '4. The token expires when the browser tab is closed.',
      '',
      '---',
      '',
      '## Rate Limits',
      '',
      '| Tier | Requests/minute | Requests/day |',
      '|---|---|---|',
      '| Free | 5 | 20 |',
      '| Pro | 60 | Unlimited |',
      '| Enterprise | Unlimited | Unlimited |',
      '',
      '---',
      '',
      '## TypeScript SDK (Coming Q3 2026)',
      '',
      'A TypeScript/JavaScript SDK is planned for Q3 2026 that will wrap all API endpoints with typed interfaces and streaming helpers.',
      '',
      '---',
      '',
      '## GET /api/status',
      '',
      'Check the current health and operational status of the DocGen AI system and underlying LLM providers.',
      '',
      '### Response',
      '',
      '| Field | Type | Description |',
      '|---|---|---|',
      '| status | string | "operational", "degraded", or "down" |',
      '| latency | number | Current average processing latency in milliseconds |',
      '| active_nodes | number | Number of Vercel edge nodes actively processing requests |',
      '| provider_status | object | Status of downstream providers (e.g. Groq) |',
      '',
      '---',
      '',
      '## GET /api/models',
      '',
      'Retrieve a list of currently supported AI models for document synthesis.',
      '',
      '### Response',
      '',
      '| Field | Type | Description |',
      '|---|---|---|',
      '| models | array | List of available models (e.g., ["llama-3.3-70b", "llama-3-8b"]) |',
      '| default_model | string | The model used if none is specified in requests |',
      '',
      '---',
      '',
      '## POST /api/webhooks',
      '',
      'Configure a webhook to receive asynchronous payloads when large-scale documentation jobs complete (Enterprise only).',
      '',
      '### Request Body',
      '',
      '| Field | Type | Required | Description |',
      '|---|---|---|---|',
      '| target_url | string | Yes | The HTTPS endpoint to deliver payloads to |',
      '| secret | string | Yes | The signing secret to verify payload authenticity |',
      '| events | array | Yes | List of events to subscribe to (e.g., ["job.completed", "job.failed"]) |',
    ].join('\n')
  },
  {
    id: 'sec-rotation',
    title: 'Sec. Rotation',
    section: 'PROTOCOLS',
    content: [
      '# Security & Key Rotation',
      '',
      '## Security Architecture',
      '',
      'DocGen AI was designed from the ground up with a zero-trust, zero-persistence security model. Your source code is your most valuable intellectual property. We never store it.',
      '',
      '## Zero-Persistence Core',
      '',
      'When you submit code to DocGen AI:',
      '',
      '1. The payload travels over TLS 1.3 to the nearest Vercel edge node.',
      '2. The edge function processes the request **entirely in RAM**.',
      '3. The Groq API receives only the prompt (your code plus instructions).',
      '4. Groq returns the generated text and **immediately discards the context**.',
      '5. The edge function streams the result back and closes the connection.',
      '',
      'At no point is your source code written to any disk, database, log file, or persistent storage.',
      '',
      '## AES-256 Session Encryption',
      '',
      'All communication between the browser and the API is protected by TLS 1.3 with AES-256-GCM cipher suites. This includes the SSE stream.',
      '',
      '## Key Rotation Protocol',
      '',
      'For Pro sessions, DocGen AI implements ephemeral key rotation:',
      '',
      '### How It Works',
      '',
      '1. On Studio initialization, the client generates a unique session seed using the Web Crypto API.',
      '2. The seed is hashed with SHA-256 to produce a session key.',
      '3. The session key is attached as a rotating token to each request.',
      '4. Each request generates a new derived key from the previous key plus a timestamp.',
      '5. If a request is replayed, the timestamp mismatch causes the token to be rejected.',
      '',
      '## Threat Model',
      '',
      '| Threat | Mitigation |',
      '|---|---|',
      '| Code exfiltration | Zero persistence — data never written to disk |',
      '| Replay attacks | Timestamp-based rotating session tokens |',
      '| Man-in-the-middle | TLS 1.3 with certificate pinning |',
      '| LLM training on submissions | Groq API contract excludes training on API inputs |',
      '| Session hijacking | Session tokens stored in sessionStorage, not cookies |',
      '| Brute force | Rate limiting at edge plus exponential backoff |',
      '',
      '## Data Retention Policy',
      '',
      '| Data Type | Retention Period |',
      '|---|---|',
      '| Source code submissions | 0 seconds (volatile memory only) |',
      '| Generated documentation | Browser session only (not persisted server-side) |',
      '| API request metadata | 7 days (for abuse prevention; no code content) |',
      '| User account data | Until account deletion |',
      '',
      '## Compliance',
      '',
      'DocGen AI\'s zero-persistence architecture makes it suitable for use in regulated environments:',
      '',
      '- **SOC 2 Type I** (in progress)',
      '- **GDPR** — No personal data created during synthesis',
      '- **HIPAA eligible** — No PHI stored (consult your compliance team)',
      '',
      '## Responsible Disclosure',
      '',
      'If you discover a security vulnerability, please report it to our team. We operate a responsible disclosure policy with a 90-day remediation window.',
    ].join('\n')
  },
  {
    id: 'deployment',
    title: 'Deployment',
    section: 'PROTOCOLS',
    content: [
      '# Deployment Guide',
      '',
      '## Overview',
      '',
      'DocGen AI is deployed on Vercel\'s global edge network. This guide covers how to deploy your own instance, configure environment variables, and set up a CI/CD pipeline.',
      '',
      '## Prerequisites',
      '',
      '- Node.js 18+',
      '- npm or yarn',
      '- A Vercel account',
      '- A Groq API key (free tier available at console.groq.com)',
      '',
      '## Quick Start',
      '',
      '### 1. Clone the Repository',
      '',
      'Run: git clone https://github.com/your-org/docgen-ai.git',
      '',
      '### 2. Install Dependencies',
      '',
      'Run: npm install',
      '',
      '### 3. Configure Environment Variables',
      '',
      'Create a .env.local file in the root directory with:',
      '',
      '- GROQ_API_KEY=your_groq_api_key_here',
      '- SECURE_SALT=your_random_32_char_salt_here',
      '- NODE_ENV=development',
      '',
      '> **Warning**: Never commit your .env.local file. It is already listed in .gitignore.',
      '',
      '### 4. Run Locally',
      '',
      'Run: npm run dev',
      '',
      'The frontend will be available at http://localhost:5173.',
      '',
      '### 5. Deploy to Production',
      '',
      'Run: vercel deploy --prod',
      '',
      'Or push to your connected GitHub repository and let Vercel deploy automatically.',
      '',
      '## Environment Variables Reference',
      '',
      '| Variable | Required | Description |',
      '|---|---|---|',
      '| GROQ_API_KEY | Required | Your Groq API key for AI synthesis |',
      '| SECURE_SALT | Optional | Salt for session token derivation |',
      '| NODE_ENV | Optional | Set to production for optimized builds |',
      '',
      '## CI/CD with GitHub Actions',
      '',
      'For automated testing before deployment, add a GitHub Actions workflow that checks out the repo, sets up Node 18, installs dependencies, and runs the build command.',
      '',
      '## Scaling Considerations',
      '',
      'Since DocGen AI is fully serverless, it scales automatically. There are no servers to provision or manage. Vercel handles:',
      '',
      '- Global load balancing',
      '- Automatic SSL certificate rotation',
      '- CDN caching for the frontend assets',
      '- Edge function replication across 40+ regions',
      '',
      '## Custom Domain',
      '',
      'To add a custom domain:',
      '',
      '1. Go to your Vercel project settings.',
      '2. Navigate to "Domains".',
      '3. Add your domain (e.g. docs.yourdomain.com).',
      '4. Follow the DNS configuration instructions.',
      '',
      '## Monitoring',
      '',
      'Vercel provides built-in analytics, function logs, and error tracking. For advanced observability, integrate with:',
      '',
      '- **Vercel Analytics** — Built-in, zero-config',
      '- **Sentry** — For error tracking and performance monitoring',
      '- **Datadog** — For infrastructure-level metrics',
    ].join('\n')
  },
  {
    id: 'refactor-ops',
    title: 'Refactor Ops',
    section: 'PROTOCOLS',
    content: [
      '# Refactor Ops & Best Practices',
      '',
      '## Overview',
      '',
      'This guide covers best practices for getting the highest quality output from DocGen AI, as well as strategies for integrating documentation generation into your refactoring workflow.',
      '',
      '## Input Optimization',
      '',
      '### 1. Modular Buffers',
      '',
      'Submit focused, single-responsibility modules for the best results. DocGen AI returns **40% higher documentation density** when processing files under 500 lines compared to large monolithic files.',
      '',
      '**Good:** Submit userAuthService.ts (250 lines, single responsibility)',
      '**Less ideal:** Submit app.ts (5,000 lines, mixed concerns)',
      '',
      '### 2. Include Type Annotations',
      '',
      'Strong typing significantly improves the quality of API reference and docstring generation. Languages with explicit types (TypeScript, Rust, Go, Java) produce measurably better output.',
      '',
      '### 3. Use Descriptive Names',
      '',
      'Code with descriptive variable and function names produces documentation that matches developer intent more accurately.',
      '',
      '### 4. Add Inline Context',
      '',
      'Use a brief comment at the top of your submitted code to give the AI context about the broader system, e.g.: "This module handles multi-currency payment processing for a B2B SaaS platform."',
      '',
      '## Refactoring Workflow Integration',
      '',
      '### The Documentation-Driven Refactor',
      '',
      '1. Submit existing legacy code to DocGen AI.',
      '2. Review the generated **Security** and **Performance** tabs for issues.',
      '3. Use the **Architecture Diagram** to understand the current coupling.',
      '4. Refactor based on the findings.',
      '5. Resubmit the refactored code to validate improvement in the **Quality Score**.',
      '',
      '### Quality Score Targets',
      '',
      '| Score | Interpretation | Action |',
      '|---|---|---|',
      '| 9.0 – 10.0 | Excellent | No action required |',
      '| 7.0 – 8.9 | Good | Minor improvements possible |',
      '| 5.0 – 6.9 | Fair | Refactoring recommended |',
      '| 3.0 – 4.9 | Poor | Significant work needed |',
      '| 0 – 2.9 | Critical | Major rewrite advised |',
      '',
      '## README Strategy',
      '',
      'Use DocGen AI\'s README synthesis for:',
      '',
      '- **Onboarding documentation** — Generate a full README for new team members before they join.',
      '- **Open-source releases** — Produce professional-grade documentation for GitHub without the manual effort.',
      '- **Client handoffs** — Generate a stakeholder-friendly summary of a delivered codebase.',
      '- **PR reviews** — Generate a diff-targeted README update when a PR changes the public API.',
      '',
      '## Diagram Best Practices',
      '',
      '### When to Use Architecture Diagrams',
      '',
      '- After adding a new service or module',
      '- Before presenting a system design to stakeholders',
      '- When debugging complex async flows',
      '- For documentation of microservice boundaries',
      '',
      '### Rendering Mermaid Output',
      '',
      'Copy the Mermaid code from the Diagram tab and paste it into mermaid.live for instant rendering, or paste directly into GitHub Markdown (renders natively).',
      '',
      '## Test Scaffolding Workflow',
      '',
      '1. Submit a module to DocGen AI.',
      '2. Open the **Tests** tab.',
      '3. Copy the generated test templates.',
      '4. Paste into your test directory.',
      '5. Fill in the expected values and run your test suite.',
      '',
      'Generated tests will cover:',
      '- Happy path scenarios',
      '- Edge cases (empty inputs, null values, boundary conditions)',
      '- Error scenarios (thrown exceptions, rejected promises)',
      '',
      '## Team Workflow',
      '',
      '| Trigger | Action |',
      '|---|---|',
      '| New feature merged | Regenerate docstrings for changed files |',
      '| API endpoint added | Regenerate API reference |',
      '| Security audit required | Run Security tab analysis |',
      '| Sprint retrospective | Run Quality Score on sprint deliverables |',
      '| Onboarding a new developer | Generate README + Architecture Diagram |',
    ].join('\n')
  },
  {
    id: 'studio',
    title: 'DocGen Studio',
    section: 'PLATFORM',
    content: [
      '# DocGen AI Studio',
      '',
      'The Studio is our premier documentation workshop. It features sub-millisecond logical decomposition and parallel synthesis across eight distinct neurological layers.',
      '',
      '## Key Features',
      '- **Parallel Sync**: Process multiple logical blocks simultaneously for ultra-fast artifacts.',
      '- **Multi-Layer Analysis**: Generates docstrings, READMEs, API guides, and architecture diagrams in one pass.',
      '- **Real-time Streaming**: Watch your documentation synthesize as the neural engine thinks.'
    ].join('\n')
  },
  {
    id: 'pricing',
    title: 'Pricing & Tiers',
    section: 'PLATFORM',
    content: [
      '# Scalable Solutions for Every Team',
      '',
      'From solo architects to sovereign enterprise clusters, DocGen AI offers performance-tuned plans.',
      '',
      '## Tier Comparison',
      '- **Base**: Core documentation for individuals.',
      '- **Architect**: Parallel sync and unlimited manifests for power users.',
      '- **Sovereign**: Full on-prem deployment and custom neural models for large organizations.'
    ].join('\n')
  },
  {
    id: 'privacy',
    title: 'Privacy Policy',
    section: 'LEGAL',
    content: [
      '# Privacy & Data Retention Policy',
      '',
      '**Last Updated:** April 2026',
      '',
      'At DocGen AI, we recognize that your source code is your most valuable asset. Our Zero-Persistence architecture ensures that your IP remains exclusively yours.',
      '',
      '## 1. Absolute Zero-Persistence',
      'The core engine processes data in volatile memory buffers. Input payloads are purged the millisecond documentation is finalized. We never write your source logic to persistent disks, databases, or log systems.',
      '',
      '## 2. Neural Processing Agreements',
      'Our AI providers (Groq, Anthropic) are bound by strict Data Processing Agreements (DPAs) that explicitly prohibit the use of your submissions for model training or future refinement.',
      '',
      '## 3. Minimal Metadata Collection',
      'We collect only what is necessary for security and abuse prevention: session IDs, language heuristics, and token volumes. IP addresses are purged periodically.',
      '',
      '## 4. Your Rights under GDPR/CCPA',
      'You have full control over your account data. Request immediate deletion or total data export at any time via our sovereign support channel.'
    ].join('\n')
  },
  {
    id: 'terms',
    title: 'Terms of Service',
    section: 'LEGAL',
    content: [
      '# Terms of Service',
      '',
      '**Last Updated:** April 2026',
      '',
      '## 1. Service Scope',
      'DocGen AI provides an automated neural documentation synthesis platform. The service is provided "as is" with no warranty regarding the absolute accuracy of the AI-generated prose.',
      '',
      '## 2. Intellectual Property Assurance',
      'You retain 100% ownership of your source code and the resulting documentation. DocGen AI claims no rights to your inputs or outputs.',
      '',
      '## 3. Usage Boundaries',
      'Users are prohibited from using the platform for malicious logical extraction or DOS attacks against the neural gateway. Exceeding rate limits may result in temporary throttle or suspension.',
      '',
      '## 4. Limitation of Liability',
      'DocGen AI is an assistant, not a replacement for human engineering review. Use the generated artifacts at your own discretion within production environments.'
    ].join('\n')
  }
];
